### ISSUE TITLE
Adding class to non-active collapse-toggle

### ISSUE THREAD

**Issue by S1SYPHOS** [cferdinandi/houdini#39]
Hey there,
I am currently enjoying your simple yet effective script, thanks. I stumbled however upon something I'd like to have implemented, maybe that's a possible enhancement, so here's the deal:

Could we add a class to the collapse-toggle whose content isn't active? I see this is kinda what's to be achieved by having collapse-text-show and -hide, but not quite the same. I'm toggling with images and don't want them to be included twice .. but asking doesn't cost anything, right?

Cheers and keep up the good work,
I love many of your scripts.

S1SYPHOS

**Comment by cferdinandi** [comment]
Not sure I follow what it is you're trying to accomplish. That collapsed element is already not visible, so what would be gained from having a class indicating such? Any content in there is hidden already.

All that said, the .active class already provides a way for you to target selectively:

```css
.collapse {
    /* Styles when hidden */
}

.collapse.active {
    /* Styles when visible */
}
```

**Comment by S1SYPHOS** [comment]
I mean the toggle itself (`.collapse-toggle`), not the content (`.collapse`). As soon as a toggle is clicked there's no way to distinguish between the one with the active class and the one that wasn't clicked. In some use cases the result you want to accomplish for the general `.collapse-toggle` differs from `.collapse-toggle.active` AND `.collapse-toggle.inactive`.

**Comment by cferdinandi** [comment]
Ah, ok. I get it now. Sounds like you want three states:

1. Never clicked.
2. Clicked and active.
3. Clicked and inactive.

This can be done today using the `callback` option in the Houdini API:

```js
houdini.init({
    callback: function ( toggle, contentID ) {

        // If toggle is now active, remove the .inactive class
        // Otherwise, add the .inactive class
        if ( toggle.classList.contains( 'active' ) ) {
            toggle.classList.remove( 'inactive' );
        } else {
            toggle.classList.add( 'inactive' );
        }
    }
});
```
