### ISSUE TITLE
initialising using JavaScript and the  hash anchor reference.

### ISSUE THREAD

**Issue by panoply** [cferdinandi/houdini#58]
Firstly, Houdini is my goto accordion. Thanks for your work and upkeep on this component. I am running into some issues on a project I am integrating this on and was hoping for some insight on how best to handle the the Hash anchor reference. The hash anchor appended to the URL eg: `#collapse` is causing some headaches when using Houdini as a Dropdown component. Is there a way to initialise and toggle the collapse via `<button></button>` using a `[data-attribute]`  because Houdini uses a link eg: `href="#collapse` to toggle the collapse I am require to attach an eventListener and  use `history.pushState` to remove the anchor tag reference, which is just not viable at all. 

Ideally, the option to toggle and initialise using JavaScript opposed to using a `<a href="#collapse"></a>` would enable a must more flexible plugin.

**Comment by cferdinandi** [comment]
This was supported in [version 8.x, available here](https://github.com/cferdinandi/houdini/tree/v8.2.1).

Alternatively, you could try using the `openContent` and `closeContent` public methods hooked into an event listener with the latest version.
