### ISSUE TITLE
collapse only section being expanded

### ISSUE THREAD

**Issue by darije** [cferdinandi/houdini#59]
HI,
thanks for the great script.

Is there a possibility to collapse/expand sections independently?
Meaning that expanding one section doesn't automatically collapse other expanded section.

Thanks!

**Comment by cferdinandi** [comment]
That's actually the default behavior. Just don't use `[data-group]`, which is what activates the accordion behavior.

**Comment by darije** [comment]
Indeed it is :)
Thanks for a quick reponse!

**Comment by cferdinandi** [comment]
My pleasure!
