### ISSUE TITLE
transitions, animations

### ISSUE THREAD

**Issue by daybugging** [cferdinandi/houdini#65]
hey there,
quick question: i wanna animate the closing / opening, could you just give me an idea how to accomplish that? maybe including it in the demo would help!

thanks for all your truly great contributions to the open source world,

one love
daybugging

**Comment by cferdinandi** [comment]
Hi there! This is something you should be able to implement via some custom CSS and the API.

When activated, the height is set to `auto`. You would add a CSS transition to animate the height. However, transitions don't work for `height: auto`, so you would either need to:

1. Add a `max-height` and animate that, which creates a weird lag on close (see https://jsfiddle.net/leaverou/zwvNY/), or...
2. Use the callback functions to explicitly set a `height` value on open, and remove it on close. You'd probably also want to adjust it on `resize`.

If you need me to write the actual code to support this, I'm happy to do so, but would require you to purchase premium support: https://gomakethings.com/support/.

Cheers!
Chris
