### ISSUE TITLE
houdini.closeContent

### ISSUE THREAD

**Issue by exdeniz** [cferdinandi/houdini#70]
if use simple houdini.closeContent('#show') without toggle.

```
Uncaught TypeError: Cannot read property 'callbackClose' of undefined on line 306
```
toggle not defined in 
```
settings.callbackClose(content, toggle)
```

**Comment by cferdinandi** [comment]
This is working on [the demo site](http://cferdinandi.github.io/houdini/).

```js
houdini.closeContent('#section1');
```

Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/) that I can look at?

**Comment by exdeniz** [comment]
https://codepen.io/anon/pen/qPjrzm?editors=1011

Click on '+'

**Comment by cferdinandi** [comment]
Got it. I was calling the wrong callback. The latest (version 9.4.1) should fix this.

https://github.com/cferdinandi/houdini/pull/63
