### ISSUE TITLE
NPM publication

### ISSUE THREAD

**Issue by icetee** [cferdinandi/houdini#78]
I install with NPM and I use webpack, but I get error:
`houdinijs__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor`

I looked at, the prev version no use Class (constructor). I read your README.md, but not compatible with prev NPM version. The last NPM version: 9.4.2

Please upgrade Houdini in NPM repository.

**Comment by icetee** [comment]
Resolve my problem: `npm install cferdinandi/houdini#master`

**Comment by cferdinandi** [comment]
I've decided to no longer publish to NPM until GitHub Actions make it something I can automate. It may seem trivial, but I manage dozens of OSS projects, and it's an extra step that I always seem to forget.

**Comment by evandiamond** [comment]
@cferdinandi Amazing plugin and feature set, nice work! Is this available on NPM yet?
