### ISSUE TITLE
Custom houdini buttons don't work as intended

### ISSUE THREAD

**Issue by mirshko** [cferdinandi/houdini#83]
It seems that even when you specify a custom button to use its not actually using it like it should be, its still adding in the default houdini button ignoring the custom one thats declared.

**Test case:** https://codepen.io/mirshko/pen/MxOpJJ

**Comment by cferdinandi** [comment]
Good catch. The demo was loading v10 instead of v11. Fixed: https://codepen.io/cferdinandi/pen/jQQgKb
