### ISSUE TITLE
Houdini removes classes from pre-existing button

### ISSUE THREAD

**Issue by jerivas** [cferdinandi/houdini#88]
Houdini removes all CSS classes from pre-existing buttons and only leaves "houdini-toggle". This makes it very hard to style buttons that are managed by Houdini

**Test case:** https://codepen.io/jerivas/pen/MWWrBXK

**Comment by hans2103** [comment]
@jerivas this issue is fixed in 11.0.4 with commit https://github.com/cferdinandi/houdini/commit/b7319d2f19ea3b548554b290bef3da219691cdb1
@cferdinandi please update https://www.npmjs.com/package/houdinijs too

**Comment by cferdinandi** [comment]
Ah apologies for never publishing to NPM. Fixed.
